language: java
install: ./gradlew desktop:dist
deploy:
  provider: releases
  api_key:
    secure: IbGNl8JcFlto1dwGdVyZDwUQpxWdBlRVgx88C27HGlvAO4BY2E0obR9hMjbGFLxjWkxO6UF8gzSCacBTROaTxTgNJER1R7sH0o20aP4sREqEykGwZ9XLEdSMIHR46gJZZgr+zlm7U8g1JFCtx8anw223EZ6ivnI2ihWQnCPsOhQG81gvWlwerH4xSo7UPHY8fDdjN/nWx4xRDS2PSnka36rjH9kj4gRlTNR1IXi0lll8MU+8yl9DMrlcdE3C1haqDnHiY6My1ZvFp08KVPIlHFjtLUdEaRRhgOVgHTkA8jAaqLEMd6kPsl2dMfXFRszJAldFmWrngwPosoFiisq+drRiwqFBIEGRu24xgVJ35/3toU/QPkbxSOPrTvYtmCaeypZQxXWse5iWv85QoV4TeHHJeJ6eWPYoXG7jixqqLMDJUjd2DUXPluP1Bnm4MkT5qFj85VkFLWprl5PpS6/BbvkxBo5ZU9PN4+YwBDurou1KEN8pHV9SvOhixVJjVdD+eFHLxc1EWW7rzGNwVZphuUSQ07iwGRPqRXV2wu8YGBO7WI5c6zGNFayKSAK6yyrwd4Z++QZp/nCNS+AxCbM+dWTgNK9/sWPTR5vV1I6ttsb5IzRxQwMJEa43cjj+2XemJcxBxFfVZMaZrBz+I87YwFz2ebRDMJqqH8Su7y1AW/c=
  file: desktop/build/libs/desktop-1.0.jar
  on:
    repo: E241/Pongz
    tags: true
